
sonar.projectKey=Malaika-report
sonar.projectName=Malaika report
sonar.sourceEncoding=UTF-8

sonar.modules=frontend,backend

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**

frontend.sonar.projectName=Frontend
frontend.sonar.sources=frontend/src
frontend.sonar.tests=frontend/src
frontend.sonar.test.inclusions=frontend/src/**/*.test.jsx,frontend/src/**/*.test.js,frontend/src/**/*.spec.jsx,frontend/src/**/*.spec.js
frontend.sonar.coverage.exclusions=frontend/src/**/*.test.jsx,frontend/src/setupTests.js,frontend/src/pages/public/**
frontend.sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

backend.sonar.projectName=Backend
backend.sonar.sources=backend/src
backend.sonar.tests=backend/tests
backend.sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info